### PR TITLE
fix: adding Karma metadata

### LINKED ISSUE #188: [Karma] Revert karma action when remove a reaction

### PR DESCRIPTION
**Pull request by YoannMa**
- Save messageId, giverId, type with the transaction
- Deleting a message with a ++/-- mention will remove the transaction
- Removing a reaction will remove the transaction
- Handle edge were only 1 transaction, or a short period between first transactions and `now()` was crashing the `getKarma` command

Closes #188 #199

### CODE REVIEW

File: src/modules/karma/listeners/reactionAdd.js [hunk 1]
```diff
@@ -33,39 +33,37 @@ module.exports = class KarmaReactionAddListener extends Listener {
...
+        const type      = Karma.TYPES.REACTION;
+        const value     = Karma.emojiToValue(reaction.emoji.identifier);
+
+        if (!value) {
+
+            return;
         }
 
-        if (member.id === author.id) {
+        console.log(user);
```
Comment (xiprox) [inline src/modules/karma/listeners/reactionAdd.js:50]: Boop

**Review by xiprox — APPROVED** [review]
